version: '3.1'
services:
  db:
    image: mysql:8.0.37
    container_name: mysql
    restart: always
    networks:
      - aluraflix
    environment:
      MYSQL_ROOT_PASSWORD: 6040

  spring:
    image: makinay/aluraflix-api:1.1.1
    container_name: aluraflix-api
    restart: always
    depends_on:
      - db
    networks:
      - aluraflix
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/aluraflix_db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 6040

networks:
  aluraflix:
    driver: bridge

