version: '3.1'
services:
  db:
    image: mysql:8.4.0
    container_name: mysql
    networks:
      - aluraflix
    environment:
      MYSQL_ROOT_PASSWORD: 6040

  spring:
    image: makinay/aluraflix-api:1.0
    container_name: aluraflix-api
    networks:
      - aluraflix
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/aluraflix_db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 6040

networks:
  aluraflix:
    driver: bridge

